insert into specialty (id, name, description, created_at, updated_at, deleted_at) values
(1,'ALERGIA E INMUNOLOGÍA', null, now(), now(), null),
(2,'CARDIOLOGÍA', null, now(), now(), null),
(3,'CIRUGÍA GENERAL', null, now(), now(), null),
(4,'CIRUGÍA INFANTIL (CIRUGÍA PEDIÁTRICA)', null, now(), now(), null),
(5,'CLÍNICA MÉDICA', null, now(), now(), null),
(6,'DERMATOLOGÍA', null, now(), now(), null),
(7,'DERMATOLOGÍA PEDIÁTRICA', null, now(), now(), null),
(8,'DIABETOLOGÍA', null, now(), now(), null),
(9,'ENDOCRINOLOGÍA', null, now(), now(), null),
(10,'ENDOCRINOLOGÍA INFANTIL', null, now(), now(), null),
(11,'GASTROENTEROLOGÍA', null, now(), now(), null),
(12,'GASTROENTEROLOGÍA INFANTIL', null, now(), now(), null),
(13,'GINECOLOGÍA', null, now(), now(), null),
(14,'HEMATOLOGÍA', null, now(), now(), null),
(15,'INFECTOLOGÍA', null, now(), now(), null),
(16,'INFECTOLOGÍA INFANTIL', null, now(), now(), null),
(17,'MEDICINA GENERAL Y/O MEDICINA DE FAMILIA', null, now(), now(), null),
(18,'NEFROLOGÍA', null, now(), now(), null),
(19,'NEFROLOGÍA INFANTIL', null, now(), now(), null),
(20,'NEUMONOLOGÍA', null, now(), now(), null),
(21,'NEUROCIRUGÍA', null, now(), now(), null),
(22,'NEUROLOGÍA', null, now(), now(), null),
(23,'NUTRICIÓN', null, now(), now(), null),
(24,'NUTRICIÓN Y ALIMENTACIÓN CLINICA INFANTOJUVENIL', null, now(), now(), null),
(25,'OBSTETRICIA', null, now(), now(), null),
(26,'ODONTOLOGÍA (R)', null, now(), now(), null),
(27,'OFTALMOLOGÍA', null, now(), now(), null),
(28,'ORTOPEDIA Y TRAUMATOLOGÍA', null, now(), now(), null),
(29,'ORTOPEDIA Y TRAUMATOLOGÍA INFANTIL', null, now(), now(), null),
(30,'OTORRINOLARINGOLOGÍA', null, now(), now(), null),
(31,'PEDIATRÍA', null, now(), now(), null),
(32,'PSICOLOGÍA CLÍNICA', null, now(), now(), null),
(33,'PSICOLOGÍA (R)', null, now(), now(), null),
(34,'PSIQUIATRÍA', null, now(), now(), null),
(35,'REUMATOLOGÍA', null, now(), now(), null),
(36,'TOCOGINECOLOGÍA', null, now(), now(), null),
(37,'UROLOGÍA', null, now(), now(), null);

