insert into comorbidity (id, name, description, created_at, updated_at, deleted_at) values
(1,'Hipertensión',null,now(),now(),null),
(2,'Diabetes',null,now(),now(),null),
(3,'Infarto',null,now(),now(),null),
(4,'ACV',null,now(),now(),null),
(5,'Cáncer',null,now(),now(),null),
(6,'Asma',null,now(),now(),null),
(7,'EPOC',null,now(),now(),null),
(8,'Hipotiroidismo',null,now(),now(),null),
(9,'Enfermedad renal',null,now(),now(),null),
(10,'Epilepsia',null,now(),now(),null),
(11,'Alergia',null,now(),now(),null),
(12,'Inmunocompromiso',null,now(),now(),null),
(13,'VIH',null,now(),now(),null),
(14,'HVC/HVB',null,now(),now(),null),
(15,'Obesidad mórbida',null,now(),now(),null),
(16,'Enfermedades hemolíticas',null,now(),now(),null),
(17,'Hepatopatía crónica',null,now(),now(),null),
(18,'Tratamiento con anticoagulantes',null,now(),now(),null),
(19,'Neumopatía crónica (EPOC)',null,now(),now(),null),
(20,'Enfermedad con compromiso inmunológico',null,now(),now(),null),
(21,'Tratamiento con quimioterapia',null,now(),now(),null),
(22,'Tratamiento con inmunosupresoras',null,now(),now(),null),
(23,'Tratamiento con corticoides a altas dosis',null,now(),now(),null),
(24,'Otras',null,now(),now(),null);

