server:
  port: 8082
spring:
  application:
    name: chronomed
  datasource:
    url: jdbc:postgresql://localhost:5432/chronomed
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

logging:
  level:
    ar.sergiovillanueva.chronomed: DEBUG
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger

httpclient:
  keycloak:
    staff:
      chronomed:
        client-id: chronomed-staff
        client-uuid: 5b475065-2e12-4727-8fe0-8e8e996f811d
        url: http://localhost:8080/admin/realms/chronomed-staff
      admincli:
        token:
          grant-type: password
          client-id: admin-cli
          username: admin
          password: secret
          url: http://localhost:8080/realms/master/protocol/openid-connect/token
    portal:
      chronomed:
        client-id: chronomed-patient
        client-uuid: e567e005-a36a-4425-a2cd-a371ab1644ec
        url: http://localhost:8080/admin/realms/chronomed-patient
      admincli:
        token:
          grant-type: password
          client-id: admin-cli
          username: admin
          password: secret
          url: http://localhost:8080/realms/master/protocol/openid-connect/token

authservice:
  resource-client: chronomed
  staff-url: http://localhost:8080/realms/chronomed-staff
  portal-url: http://localhost:8080/realms/chronomed-patient
