spring:
  application:
    name: chronomed
  datasource:
    url: jdbc:postgresql://localhost:5432/chronomed
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

logging:
  level:
    ar.sergiovillanueva.chronomed: DEBUG

springdoc:
  swagger-ui:
    path: /swagger
